# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-02-16 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='地区名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='areas.Areas', verbose_name='上级行政区')),
            ],
            options={
                'verbose_name_plural': '省市区',
                'verbose_name': '省市区',
                'db_table': 'tb_areas',
            },
        ),
        migrations.RemoveField(
            model_name='areasmodel',
            name='parent',
        ),
        migrations.DeleteModel(
            name='AreasModel',
        ),
    ]
