# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-03-23 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='specs',
            field=models.CharField(default=1, max_length=99, verbose_name='商品属性'),
            preserve_default=False,
        ),
    ]
