# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-03-13 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=32, verbose_name='广告类别')),
            ],
            options={
                'verbose_name': '广告类别',
                'db_table': 'tb_ad_category',
                'verbose_name_plural': '广告类别',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('url', models.CharField(max_length=256, verbose_name='内容链接')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图片')),
                ('text', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
                ('discountprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='折后价格')),
                ('sequence', models.IntegerField(verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '广告内容',
                'db_table': 'tb_content',
                'verbose_name_plural': '广告内容',
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cid', models.CharField(max_length=12, verbose_name='内容id')),
                ('title', models.CharField(max_length=64, verbose_name='内容标题')),
                ('adCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contents.AdCategory', verbose_name='广告类别')),
            ],
            options={
                'verbose_name': '内容类别',
                'db_table': 'tb_content_category',
                'verbose_name_plural': '内容类别',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contents.ContentCategory', verbose_name='类别'),
        ),
    ]
